version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/API"
    schedule:
      interval: "weekly"
