name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/API/**'
      - 'src/client/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/API/**'
      - 'src/client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: |
        docker compose up -d
